version: '3.8'

services:
    postgres:
        image: postgres:16.2
        ports:
            - 5432:5432
        volumes:
            - postgresdb:/var/lib/postgresql/data
        container_name: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - node-app
    node-app:
        build: ./
        image: node-app:1.0
        container_name: node-app
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
        ports:
            - 3000:3000
        depends_on:
            - postgres
        networks:
            - node-app

networks:
    node-app:
        driver: bridge

volumes:
    postgresdb:
