app:
    port:
    replicas:
    label:

ingress:
    host:
    class:

secret:
    postgres_user:
    postgres_password:
    postgres_db_name:

config:
    hostname:
    secret:
    pg_port:

container:
    containerName:
    image:
    tag:

defaultTag:
    albselector:
