apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels: 
    app: {{ .Values.app.label }}
data:
  POSTGRES_HOST: {{ .Values.config.hostname }}
  POSTGRES_PORT: "{{ .Values.config.pg_port }}"