apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secret.postgres_user }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgres_password }}
  POSTGRES_DB: {{ .Values.secret.postgres_db_name }}
