apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Values.app.label }}
spec:
  selector: 
    app: node-app
  ports:
    - port: 443
      name: https
      protocol: TCP
      targetPort: {{ .Values.app.port }}

