apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-service
  labels:
    app: node-app-service
spec:
  selector: 
    app: node-app
  ports:
      name: https
      protocol: TCP
      port: 443
      targetPort: 3000

