name: Docker

on:
    workflow_dispatch:
    push:
        tags: ['[0-9]+.[0-9]+.[0-9]+']

env:
    # Use docker.io for Docker Hub if empty
    REGISTRY: ghcr.io
    # github.repository as <account>/<repo>
    IMAGE_NAME: ${{ github.repository }}
    GITHUB_USERNAME: milan0161
    TAG: ${GITHUB_REF#refs/tags/}

jobs:
    build:
        #if: startsWith(github.ref, 'refs/tags/') && github.ref == '^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$'
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            # This is used to complete the identity challenge
            # with sigstore/fulcio when running outside of PRs.
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # Login against a Docker registry except on PR
            # https://github.com/docker/login-action
            - name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
              # run: docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.Action_Token }}

            - name: Validate tag format
              run: |
                  if [[ ! "${{ env.TAG }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                   echo "Tag does not match the semantic versioning pattern"
                   exit 1

            - name: Build Docker mage
              run: docker build . -t ${{ env.REGISTRY }}/${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

            - name: Push Docker Image
              run: docker push ${{ env.REGISTRY }}/${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
