name: Docker

on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Semantic version'
                required: true
                type: string
    push:
        tags: ['[0-9]+.[0-9]+.[0-9]+']

env:
    # Use docker.io for Docker Hub if empty
    REPOSITORY: node-app-repo
    IMAGE_TAG: ${{ inputs.tag || github.refs.tags}}
    IMAGE_NAME: ${{ github.repository}}
    ASSUMABLE_ROLE: ${{ secrets.ASSUMABLE_ROLE }}
    AWS_REGION: eu-central-1

jobs:
    build:
        #if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
              with:
                  role-to-assume: ${{env.ASSUMABLE_ROLE}}
                  aws-region: ${{env.AWS_REGION}}
                  mask-aws-account-id: 'true'

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
              with:
                  mask-password: 'true'

            - name: Build and push Docker image
              uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
              with:
                  context: .
                  push: true
                  tags: ${{ steps.login-ecr.outputs.registry}}/${{ env.REPOSITORY }}:docker-${{ env.IMAGE_TAG}}
