name: Docker

on:
    workflow_dispatch:
    #push:
    #tags: ['[0-9]+.[0-9]+.[0-9]+']

env:
    # Use docker.io for Docker Hub if empty
    GITHUB_USERNAME: milan016
    REGISTRY: node-app-repo
    IMAGE_NAME: ${{ github.repository }}
    ASSUMABLE_ROLE: ${{ secrets.ASSUMABLE_ROLE }}
    AWS_REGION: eu-central-1

jobs:
    build:
        #if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
              with:
                  role-to-assume: ${{env.ASSUMABLE_ROLE}}
                  aws-region: ${{env.AWS_REGION}}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build Docker mage
              run: docker build . -t ${{ env.REGISTRY }}/${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

            - name: Push Docker Image
              run: docker push ${{ env.REGISTRY }}/${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
